---
# tasks file for skupper_token
- name: Include platform specific tasks
  ansible.builtin.include_tasks: "{{ skupper_platform }}-tasks.yml"

- name: Common tasks
  ansible.builtin.include_tasks: common-tasks.yml
  when: skupper_token_allowed is defined and skupper_token_allowed | bool
