---
- name: Validating if a token can be created
  ansible.builtin.set_fact:
    skupper_token_allowed: true
  when: init is not defined or init['ingress'] is not defined or init['ingress'] != 'none'
