- name: Preparing update command
  ansible.builtin.set_fact:
    skupper_update_command:
      - skupper
      - update
      - --platform
      - "{{ skupper_platform }}"

- name: Adding --kubeconfig
  ansible.builtin.set_fact:
    skupper_update_command: "{{ skupper_update_command + ['--kubeconfig', skupper_kubeconfig] }}"
  when: kubeconfig is defined and kubeconfig | length() > 0

- name: Adding --context
  ansible.builtin.set_fact:
    skupper_update_command: "{{ skupper_update_command + ['--context', skupper_context] }}"
  when: context is defined and context | length() > 0

- name: Adding --namespace
  ansible.builtin.set_fact:
    skupper_update_command: "{{ skupper_update_command + ['--namespace', skupper_namespace] }}"
  when: namespace is defined and namespace | length() > 0

- name: Adding --force-restart
  ansible.builtin.set_fact:
    skupper_update_command: "{{ skupper_update_command + ['--force-restart'] }}"
  when: update['forceRestart'] is defined and ( update.forceRestart | bool )
