---
# tasks file for skupper_update
- name: Include platform specific tasks
  ansible.builtin.include_tasks: "{{ skupper_platform }}-tasks.yml"

# executing and validating result
- name: Executing skupper update
  ansible.builtin.command:
    argv: "{{ skupper_update_command }}"
  register: updateStatus
  changed_when: not updateStatus.failed
