---
# tasks file for skupper_common
- name: Defining default facts
  ansible.builtin.set_fact:
    platform: "{{ platform if platform != '' else default_platform }}"

- name: Validating skupper platform
  ansible.builtin.fail:
    msg: "Invalid platform - valid platforms: {{ skupper_valid_platforms }}"
  when: platform not in skupper_valid_platforms
