---
# tasks file for skupper_common
- name: Validating skupper platform
  ansible.builtin.fail:
    msg: "Invalid platform - valid platforms: {{ skupper_valid_platforms }}"
  when: skupper_platform not in skupper_valid_platforms
