---
- name: Adding --kubeconfig
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--kubeconfig', skupper_kubeconfig] }}"
  when: skupper_kubeconfig | length() > 0

- name: Adding --context
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--context', skupper_context] }}"
  when: skupper_context | length() > 0

- name: Adding --namespace
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--namespace', skupper_namespace] }}"
  when: skupper_namespace | length() > 0

- name: Adding --ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-host', skupper_init_kubernetes_ingressHost] }}"
  when: skupper_init_kubernetes_ingressHost is defined

- name: Adding --create-network-policy
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--create-network-policy=' + skupper_init_kubernetes_createNetworkPolicy] }}"
  when: skupper_init_kubernetes_createNetworkPolicy is defined

- name: Adding --enable-service-sync
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-service-sync=' + skupper_init_kubernetes_enableServiceSync] }}"
  when: skupper_init_kubernetes_enableServiceSync is defined

- name: Adding --service-sync-site-ttl
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--service-sync-site-ttl', skupper_init_kubernetes_serviceSyncSiteTtl] }}"
  when: skupper_init_kubernetes_serviceSyncSiteTtl is defined

- name: Adding --enable-rest-api
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-rest-api=' + skupper_init_kubernetes_enableRestApi] }}"
  when: skupper_init_kubernetes_enableRestApi is defined

- name: Adding --enable-cluster-permissions
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-cluster-permissions=' + skupper_init_kubernetes_enableClusterPermissions] }}"
  when: skupper_init_kubernetes_enableClusterPermissions is defined

- name: Adding --enable-skupper-events
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--enable-skupper-events=' + skupper_init_kubernetes_enableSkupperEvents] }}"
  when: skupper_init_kubernetes_enableSkupperEvents is defined

- name: Adding --console-ingress
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--console-ingress', skupper_init_kubernetes_consoleIngress] }}"
  when: skupper_init_kubernetes_consoleIngress is defined

- name: Adding --annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--annotations', item] }}"
  with_items: "{{ skupper_init_kubernetes_annotations }}"
  when: skupper_init_kubernetes_annotations | length() > 0

- name: Adding --ingress-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-annotations', item] }}"
  with_items: "{{ skupper_init_kubernetes_ingressAnnotations }}"
  when: skupper_init_kubernetes_ingressAnnotations | length() > 0

- name: Adding --router-service-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-service-annotations', item] }}"
  with_items: "{{ skupper_init_kubernetes_routerServiceAnnotations }}"
  when: skupper_init_kubernetes_routerServiceAnnotations | length() > 0

- name: Adding --controller-service-annotations
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-service-annotations', item] }}"
  with_items: "{{ skupper_init_kubernetes_controllerServiceAnnotations }}"
  when: skupper_init_kubernetes_controllerServiceAnnotations | length() > 0

- name: Adding --routers
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--routers', skupper_init_kubernetes_routers] }}"
  when: skupper_init_kubernetes_routers is defined

- name: Adding --router-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu', skupper_init_kubernetes_routerCpu] }}"
  when: skupper_init_kubernetes_routerCpu is defined

- name: Adding --router-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory', skupper_init_kubernetes_routerMemory] }}"
  when: skupper_init_kubernetes_routerMemory is defined

- name: Adding --router-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-cpu-limit', skupper_init_kubernetes_routerCpuLimit] }}"
  when: skupper_init_kubernetes_routerCpuLimit is defined

- name: Adding --router-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-memory-limit', skupper_init_kubernetes_routerMemoryLimit] }}"
  when: skupper_init_kubernetes_routerMemoryLimit is defined

- name: Adding --router-node-selector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-node-selector', skupper_init_kubernetes_routerNodeSelector] }}"
  when: skupper_init_kubernetes_routerNodeSelector is defined

- name: Adding --router-pod-affinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-affinity', skupper_init_kubernetes_routerPodAffinity] }}"
  when: skupper_init_kubernetes_routerPodAffinity is defined

- name: Adding --router-pod-antiaffinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-pod-antiaffinity', skupper_init_kubernetes_routerPodAntiaffinity] }}"
  when: skupper_init_kubernetes_routerPodAntiaffinity is defined

- name: Adding --router-ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-ingress-host', skupper_init_kubernetes_routerIngressHost] }}"
  when: skupper_init_kubernetes_routerIngressHost is defined

- name: Adding --router-load-balancer-ip
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--router-load-balancer-ip', skupper_init_kubernetes_routerLoadBalancerIp] }}"
  when: skupper_init_kubernetes_routerLoadBalancerIp is defined

- name: Adding --controller-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu', skupper_init_kubernetes_controllerCpu] }}"
  when: skupper_init_kubernetes_controllerCpu is defined

- name: Adding --controller-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory', skupper_init_kubernetes_controllerMemory] }}"
  when: skupper_init_kubernetes_controllerMemory is defined

- name: Adding --controller-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-cpu-limit', skupper_init_kubernetes_controllerCpuLimit] }}"
  when: skupper_init_kubernetes_controllerCpuLimit is defined

- name: Adding --controller-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-memory-limit', skupper_init_kubernetes_controllerMemoryLimit] }}"
  when: skupper_init_kubernetes_controllerMemoryLimit is defined

- name: Adding --controller-node-selector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-node-selector', skupper_init_kubernetes_controllerNodeSelector] }}"
  when: skupper_init_kubernetes_controllerNodeSelector is defined

- name: Adding --controller-pod-affinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-affinity', skupper_init_kubernetes_controllerPodAffinity] }}"
  when: skupper_init_kubernetes_controllerPodAffinity is defined

- name: Adding --controller-pod-antiaffinity
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-pod-antiaffinity', skupper_init_kubernetes_controllerPodAntiaffinity] }}"
  when: skupper_init_kubernetes_controllerPodAntiaffinity is defined

- name: Adding --controller-ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-ingress-host', skupper_init_kubernetes_controllerIngressHost] }}"
  when: skupper_init_kubernetes_controllerIngressHost is defined

- name: Adding --controller-load-balancer-ip
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--controller-load-balancer-ip', skupper_init_kubernetes_controllerLoadBalancerIp] }}"
  when: skupper_init_kubernetes_controllerLoadBalancerIp is defined

- name: Adding --config-sync-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu', skupper_init_kubernetes_configSyncCpu] }}"
  when: skupper_init_kubernetes_configSyncCpu is defined

- name: Adding --config-sync-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory', skupper_init_kubernetes_configSyncMemory] }}"
  when: skupper_init_kubernetes_configSyncMemory is defined

- name: Adding --config-sync-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-cpu-limit', skupper_init_kubernetes_configSyncCpuLimit] }}"
  when: skupper_init_kubernetes_configSyncCpuLimit is defined

- name: Adding --config-sync-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--config-sync-memory-limit', skupper_init_kubernetes_configSyncMemoryLimit] }}"
  when: skupper_init_kubernetes_configSyncMemoryLimit is defined

- name: Adding --flow-collector-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-cpu', skupper_init_kubernetes_flowCollectorCpu] }}"
  when: skupper_init_kubernetes_flowCollectorCpu is defined

- name: Adding --flow-collector-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-memory', skupper_init_kubernetes_flowCollectorMemory] }}"
  when: skupper_init_kubernetes_flowCollectorMemory is defined

- name: Adding --flow-collector-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-cpu-limit', skupper_init_kubernetes_flowCollectorCpuLimit] }}"
  when: skupper_init_kubernetes_flowCollectorCpuLimit is defined

- name: Adding --flow-collector-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--flow-collector-memory-limit', skupper_init_kubernetes_flowCollectorMemoryLimit] }}"
  when: skupper_init_kubernetes_flowCollectorMemoryLimit is defined

- name: Adding --external-prometheus-server
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--external-prometheus-server', skupper_init_kubernetes_externalPrometheusServer] }}"
  when: skupper_init_kubernetes_externalPrometheusServer is defined

- name: Adding --prometheus-cpu
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-cpu', skupper_init_kubernetes_prometheusCpu] }}"
  when: skupper_init_kubernetes_prometheusCpu is defined

- name: Adding --prometheus-memory
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-memory', skupper_init_kubernetes_prometheusMemory] }}"
  when: skupper_init_kubernetes_prometheusMemory is defined

- name: Adding --prometheus-cpu-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-cpu-limit', skupper_init_kubernetes_prometheusCpuLimit] }}"
  when: skupper_init_kubernetes_prometheusCpuLimit is defined

- name: Adding --prometheus-memory-limit
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-memory-limit', skupper_init_kubernetes_prometheusMemoryLimit] }}"
  when: skupper_init_kubernetes_prometheusMemoryLimit is defined

- name: Adding --prometheus-auth
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-auth', skupper_init_kubernetes_prometheusAuth] }}"
  when: skupper_init_kubernetes_prometheusAuth is defined

- name: Adding --prometheus-user
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-user', skupper_init_kubernetes_prometheusUser] }}"
  when: skupper_init_kubernetes_prometheusUser is defined

- name: Adding --prometheus-password
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--prometheus-password', skupper_init_kubernetes_prometheusPassword] }}"
  when: skupper_init_kubernetes_prometheusPassword is defined
