---
- name: Adding --ingress-host
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-host', item] }}"
  with_items: "{{ skupper_init_podman_ingressHosts }}"
  when: skupper_init_podman_ingressHosts is defined and skupper_init_podman_ingressHosts | length() > 0

- name: Adding --ingress-bind-ip
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--ingress-bind-ip', item] }}"
  with_items: "{{ skupper_init_podman_ingressBindIps }}"
  when: skupper_init_podman_ingressBindIps is defined and skupper_init_podman_ingressBindIps | length() > 0

- name: Adding --bind-port
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--bind-port', skupper_init_podman_bindPort] }}"
  when: skupper_init_podman_bindPort is defined

- name: Adding --bind-port-edge
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--bind-port-edge', skupper_init_podman_bindPortEdge] }}"
  when: skupper_init_podman_bindPortEdge is defined

- name: Adding --container-network
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--container-network', skupper_init_podman_containerNetwork] }}"
  when: skupper_init_podman_containerNetwork is defined

- name: Adding --podman-endpoint
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--podman-endpoint', skupper_init_podman_podmanEndpoint] }}"
  when: skupper_init_podman_podmanEndpoint is defined

- name: Adding --bind-port-flow-collector
  ansible.builtin.set_fact:
    skupper_init_command: "{{ skupper_init_command + ['--bind-port-flow-collector', skupper_init_bindPortFlowCollector] }}"
  when: skupper_init_bindPortFlowCollector is defined
