---
- name: "Validating ingress host"
  ansible.builtin.fail:
    msg: "Ingress host is required"
  when:
    - skupper_init_ingress is not defined or skupper_init_ingress != 'none'
    - skupper_init_flags['podman'].ingressHosts | length < 1)
