---
# tasks file for skupper_delete
- name: Include platform specific tasks
  ansible.builtin.include_tasks: "{{ skupper_platform }}-tasks.yml"

# executing and validating result
- name: Executing skupper delete
  ansible.builtin.command:
    argv: "{{ skupper_delete_command }}"
  register: deleteStatus
  changed_when: not deleteStatus.failed
  failed_when: >
    deleteStatus.failed and
    "Skupper not installed in" not in deleteStatus.stderr_lines[0] and
    "Skupper is not enabled for" not in deleteStatus.stderr_lines[0]
