---
- name: Converge
  hosts: all
  vars: 
    skupper_platform: podman
    skupper_init_ingress: external
    skupper_init_podman_ingressHosts: [ instance ]
  roles:
    - role: skupper_cli_install
    - role: skupper_init
