---
# defaults file for skupper_cli_install
skupper_cli_install_version: latest
skupper_cli_install_os: "{{ 'linux' if ansible_system == 'Linux' else 'win' if ansible_os_family == 'Windows' else 'mac' if ansible_os_family == 'Darwin' }}"
skupper_cli_install_arch: "{{ arch_values[ansible_architecture] | default('amd64') }}"
skupper_cli_install_latest_release_url: "https://api.github.com/repos/skupperproject/skupper/releases/latest"
skupper_cli_install_download_url_base: "https://github.com/skupperproject/skupper/releases/download"
skupper_cli_install_location: /opt/skupper
