---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      fqcn: 'skupper/network'
      molecule_tests: >-
          [ "default" ]
